FROM python:3.9-slim

WORKDIR /app

# Sadece API, Kafka ve İstek kütüphaneleri (Eksiksiz)
RUN pip install --no-cache-dir \
    fastapi \
    uvicorn \
    kafka-python \
    requests \
    python-dotenv

# API Dosyaları
COPY ingestion_api.py .
COPY fake_company.py .

CMD ["uvicorn", "ingestion_api:app", "--host", "0.0.0.0", "--port", "8000"]