FROM confluentinc/cp-kafka-connect:7.4.0

USER root
RUN yum install -y curl

# 1. Datagen Kurulumu
RUN confluent-hub install --no-prompt confluentinc/kafka-connect-datagen:0.6.0

# 2. HTTP Kurulumu (Manuel)
RUN mkdir -p /usr/share/confluent-hub-components/kafka-connect-http
RUN curl -L -o /usr/share/confluent-hub-components/kafka-connect-http/kafka-connect-http-0.8.11.jar https://github.com/castorm/kafka-connect-http/releases/download/v0.8.11/kafka-connect-http-0.8.11.jar

USER appuser