global:
  scrape_interval: 15s # 5s yerine 15s yaparak CPU ve RAM'i koruyoruz
  evaluation_interval: 15s

scrape_configs:
  # Prometheus'un kendi kendini izlemesi
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090'] # localhost yerine servis ismi daha sağlamdır

  # Konteyner metrikleri (RAM, CPU, Network)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']